### ISSUE TITLE
Easier access to Learn IDE

### ISSUE THREAD

**Issue by MysticRiver** [learn-co-curriculum/html-css-how-the-web-works#2]
I think that there should be easier access to the Learn IDE. It should be a prominent link on a menu or on each page. The link to open each code challenge should lead to a link to download the IDE if it is not already on the device.

My laptop died and I wanted to access the course on my desktop, but it took a long time for me to figure out exactly where the Learn IDE was so I could continue working on the course.

You really want this to be seamless and device agnostic so That one can easily pickup on the lesson regardless of the device they use.

**Comment by AnnJohn** [comment]
hi @MysticRiver thanks again for your feedback. Definitely aware of the issue of having the Learn IDE be able to work on multiple devices. 

In terms of having a prominent link or menu, could you actually file that as a bug report so that our product team can be aware of it? If you hover over your profile pic in Learn, you'll see an option to Report a Bug from a drop down menu. 

Thanks!
